version: "3"

services:
  nodejs:
    container_name: "biometrics"
    image: node:20.12.1
    restart: always
    working_dir: /api
    volumes:
      - ./:/api
    command: bash -c "npm install && npm start"
    ports:
     - "9092:9092"
    environment:
      - PORT=9092

    labels:
      - traefik.enable=true
      - traefik.http.services.biometrics.loadbalancer.server.port=9000
      - traefik.http.routers.biometrics.rule=Host("psdbm.hris.mweeb.com")
      - traefik.http.routers.biometrics.entrypoints=web
      - traefik.http.routers.biometrics_secured.rule=Host("psdbm.hris.mweeb.com")
      - traefik.http.routers.biometrics_secured.entrypoints=websecure
      - traefik.http.routers.biometrics_secured.tls.certresolver=myhttpchallenge
      - traefik.http.routers.biometrics.middlewares=redirect@file


networks:
  default:
    external:
      name: server-network